#!/bin/sh
### BEGIN INIT INFO
# Provides:            inet
# Required-Start:      cmdline fstab
# Should-Start:        $syslog
# X-Start-Before:      udev uevent
# Required-Stop:
# Should-Stop:
# Default-Start:       3 4 5
# Default-Stop:
# Short-Description:   inetd
# Description:         inetd
### END INIT INFO

. /etc/init.d/template
. uevent-sh-functions

NAME=inetd
PIDFILE="/var/run/$NAME.pid"
ARGS="--lockfile $LOCKFILE --pidfile $PIDFILE"

start() {
	start_daemon $ARGS -- "$NAME"
	RETVAL=$?
	return $RETVAL
}

stop() {
	stop_daemon $ARGS -- "$NAME"
	RETVAL=$?
	return $RETVAL
}

switch "${1-}"
