#!/bin/sh

. uevent-sh-functions

handler() {
	rm -f "$e" ||:
	mkdir -p -- "/.initrd/isolate/$NAME"
	isolatectl start "$NAME"
}

for e in "$eventdir"/isolation.*; do
	[ -f "$e" ] || break
	( . "$e"; handler; ) ||:
done
