#!/bin/sh -efu

cfgfile='/etc/inetd.conf'
sockfile="/.initrd/isolate/$CONTAINER_NAME/sock"

[ ! -e "$sockfile" ] ||
	exit 0

update_config()
{
	if [ -f "$cfgfile" ]; then
		local svc dummy
		while read svc dummy; do
			[ "$sockfile" != "$svc" ] ||
				return 0
		done < "$cfgfile"
	fi
	printf >> "$cfgfile" \
	'%s stream unix nowait root /sbin/initramfs-shell' "$sockfile"
}

update_config

/etc/rc.d/init.d/inet condstop
/etc/rc.d/init.d/inet start
